name: quick_pm
description: A new Flutter project for QuickPM.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  go_router: ^12.1.0
  flutter_markdown: ^0.6.18+1
  intl: ^0.19.0
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  firebase_core: ^4.3.0
  cloud_firestore: ^6.1.1
  firebase_auth: ^6.1.3
  google_generative_ai: ^0.4.6  # Gemini 2.0 Flash Developer API



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
